http://ju.outofmemory.cn/entry/218569
binascii.b2a_base64  binascii.b2a_base64(os.urandom(24))[:-1]
sha1(os.urandom(24)).hexdigest()


https://api.weibo.com/oauth2/authorize?client_id=868483214&response_type=code&redirect_uri=da9d5027adec1da4449ee5de0dd31c94
https://api.weibo.com/oauth2/access_token?client_id=868483214
&client_secret=da9d5027adec1da4449ee5de0dd31c94&grant_type=authorization_code&redirect_uri=YOUR_REGISTERED_REDIRECT_URI&code=CODE
